### PR TITLE
Beta 11 - Fixes write-safety issue, adds linting and fixes linting warnings/errors.

### LINKED ISSUE #53: Onesignal Version and Build Number Being not Set Properly
Hi,

First of all, thanks for addressing #48 so fast!

Just one thing is when I run `expo prebuild --platform ios`, only one of `{{BUNDLE_VERSION}}` and  `{{BUNDLE_SHORT_VERSION}}` seems to be set properly.

I could be wrong, but I think it is because `updateNSEBundleShortVersion` and `updateNSEBundleVer` write the same file at the same time. Could you look into this?

Thank you!

```js
  NseUpdaterManager.updateNSEBundleVersion(bundleVersion ?? DEFAULT_BUNDLE_VERSION);
   NseUpdaterManager.updateNSEBundleShortVersion(bundleShortVersion ?? DEFAULT_BUNDLE_SHORT_VERSION);
```

### PR DESCRIPTION
**Pull request by rgomezp**
# One line description
Fixes write-safety issue, adds linting and fixes linting warnings/errors.

# Details
## 1. Linting
Previously wasn't using linting. This PR adds an ESLint file and fixes lint issues.

## 2. NSE Updater Write Safety
NSE updater helper functions were previously writing to the entitlements & plist files asynchronously. We should await on each to ensure we don't have multiple writes to the same file at once (which is unsafe).

Resolves #53 

## 3. ReaderManager renamed to FileManager + new write helper function
Instead of creating a "WriterManager", we repurpose the `ReaderManager` class by renaming it to `FileManager` and adding a synchronized write helper function (synchronous in the sense that it block further execution until complete).

## 4. Other changes
* NSE target name: a value that is used several places and never changes - makes sense to add to ios constants file
* Other nits such as import cleanups

### CODE REVIEW

**Review by jkasten2 — CHANGES_REQUESTED** [review]
This PR does a lot of different things. While the commits a small and easy to read it is still a bit hard to understand the full scope changes at a glance.

Left a few small comments around Promise and small nit on formatting.

File: support/NseUpdaterManager.ts [hunk 1]
```diff
@@ -1,42 +1,60 @@
...
-    let plistFile = await ReaderManager.readFile(plistFilePath);
-    plistFile = plistFile.replace(BUNDLE_VERSION_TEMPLATE_REGEX, version);
-
-    fs.writeFile(plistFilePath, plistFile, 'utf-8', err => {
-      logIfError(err);
+  async updateNSEEntitlements(groupIdentifier: string): Promise<void> {
+    const entitlementsFilePath = `${this.nsePath}/${entitlementsFileName}`;
+
+    return new Promise((resolve, reject) => {
+      FileManager.readFile(entitlementsFilePath).then(async entitlementsFile => {
```
[the remark this answers is not in the document]
Comment (rgomezp) [reply support/NseUpdaterManager.ts:23]: The reason is that promise executor functions should not be `async`.

e.g: `Promise(async (resolve, reject) => {` throws an error.

I could stick to only use `.then` but that would include nested `.then` callbacks. This is fine, but get's a bit hairy. I'm open to considering other alternatives.

File: support/NseUpdaterManager.ts [hunk 2]
```diff
@@ -1,42 +1,43 @@
...
-    fs.writeFile(entitlementsFilePath, entitlementsFile, 'utf-8', (err) => {
-      logIfError(err);
-    })
+    await FileManager.writeFile(entitlementsFilePath, entitlementsFile);
   }
 
-  static async updateNSEBundleVersion(version: string) {
-    let plistFile = await ReaderManager.readFile(plistFilePath);
+  async updateNSEBundleVersion(version: string): Promise<void> {
+    console.log("updateNSEBundleVersion:", version);
```
Comment (jkasten2) [inline support/NseUpdaterManager.ts:27]: Instead of doing `console.log` here shouldn't this call `OneSignalLog.log` instead?

There are more lines in this comment adding `console.log` below.

**Review by jkasten2 — APPROVED** [review]
Thanks for cleaning up the `Promises` in `NseUpdaterManager.ts`, this looks much better and don't see any lint warnings on them either.

I did leave a comment about the usage of `console.log`, feel free to make the fix and merge and release without another approval.

File: support/NseUpdaterManager.ts (hunk 2 above)
Comment (rgomezp) [reply support/NseUpdaterManager.ts]: for the record: it was an accident!
